version: '3.5'
services:
  proxy:
    image: traefik
    container_name: proxy
    networks:
      - overlay
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./certs:/etc/ssl/certs/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
     - traefik.enable=true
     - traefik.frontend.rule=Host:traefik.example.org
     - traefik.backend=traefik
     - traefik.port=8080
    restart: on-failure

  joiner:
    build:
      context: ./network-joiner
    networks:
      - overlay
    container_name: joiner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./network-joiner/dpnj.py:/app/dpnj.py
    restart: on-failure

networks:
  overlay:
    name: proxy_overlay
